Packer base
Otus-DevOps-2021-02/KIT-IT_infra pull request #3
Opened 2021-04-01 18:26 UTC by KIT-IT

# Выполнено ДЗ №

 - [X ] Основное ДЗ
 - [ X] Задание со *

## В процессе сделано:
Параметризовали файл.

Запекли кекс Immutable infrastructure

## Как запустить проект:
 - Описание в Readme

## Как проверить работоспособность:
 - Например, перейти по ссылке http://ipinstanse:9292

## PR checklist
 - [ ] Выставил label с номером домашнего задания
 - [ ] Выставил label с темой домашнего задания

2021-04-03 10:30 UTC, mrgreyves requested changes
Здравствуйте!) Добавьте в репозиторий файлик .github/auto_assign.yml
с содержимым:
```
# Set to true to add assignees to pull requests
addAssignees: true

# A list of reviewers to be added to pull requests (GitHub user name)
reviewers: 
  - express42-bot
 ```
Тогда все будет хорошо =)

2021-04-08 17:12 UTC, KIT-IT commented
@mrgreyves так он уже добавлен же. Посмотрите.

2021-04-08 17:21 UTC, KIT-IT commented
@mrgreyves Готово. Был именован через "-". Извините

2021-04-09 07:02 UTC, mrgreyves approved these changes
Здравствуйте!) Апрув!)

2021-04-15 18:54 UTC, merged